add someone assert, add test_sozdanie_bronirovaniya_s_nepolnymi_dannymi
IVikaQA/BookingAPITests pull request #9
Opened 2024-10-25 20:38 UTC by IVikaQA

1)Добавила несколько проверок в тест test_create_booking_with_dynamic_dates
1.Проверка: Сколько выполняется запрос ?
2.Проверка: Время выполнения запроса меньше 1000 миллисекунд 
3.Проверка:Провеерка статуса-кода
Вот здесь я не добилась результата и хотела спросить совета. Я пробовала добавить метод get_response_status_code в класс ApiClient и потом в тесте вызвать этот метод и сравнить ответ, НО 1-Возвращается None 2)Если посмотреть метод CreateBooking в Postman, то там будет в ответе: JSON и 200 OK

Ведь статус код есть: 200 OK, Но как проверить ?

2)Добавила тест: test_sozdanie_bronirovaniya_s_nepolnymi_dannymi 
Здесь не знаю как быть со статус-кодом: Возвращается 500 Как быть ?

2024-10-25 21:13 UTC, IVikaQA commented
Совсем забыла пока пыталась разобраться как вытащить статус код при создании бронирования и вот еще добавила тест test_sozdanie_bronirovaniya_s_pustym_JSON,test_sozdanie_bronirovaniya_s_nevernymi_dannymi НО нет обработки ошибки и я не знаю, как обрабатывать ошибку в этих тестах, прошу подсказать

2024-10-26 12:55 UTC, TsakunovR requested changes

2024-10-26 12:55 UTC, TsakunovR commented on tests/test_create_booking.py
> +    status_code = api_client.get_response_status_code(created_booking_response)
Вот так проверяем статус код assert response.status_code == 200

2024-10-26 12:55 UTC, TsakunovR commented on core/clients/api_client.py
> +    def get_response_status_code(self, booking_id):
Этот метод не нужен. Статус код мы провеем в самом тесте. Ты его в тестах уже проверяешь.

2024-10-29 20:25 UTC, IVikaQA commented
1)Убрала в классе ApiClient отдельный метод для возврата статус-кода
2)В классе test_create_booking.py убрала проверку на статус-код 
3)Какие добавить проверки в тесты: test_sozdanie_bronirovaniya_s_nevernymi_dannymi, test_sozdanie_bronirovaniya_s_pustym_JSON ? Пока что я просто отправила в них запросы

2024-11-02 17:04 UTC, IVikaQA commented
1)Исправила названия шагов в тестах с русских на английские
2)Про слова "Какие то проверки" поняла так: Просто написала тест, НО проверки не добавила так как такие ситуации разрабами не предусмотрены

2024-11-03 15:45 UTC, TsakunovR approved these changes

2024-11-03 19:23 UTC, merged